### ISSUE TITLE
임시 파일에 대한 처리

### ISSUE THREAD

**Issue by jae637** [jk960903/InterViewQA#4]
~임시 파일에 대한 처리를 .gitignore 로 처리해보자

**Comment by jae637** [comment]
해결해 주세요;; 왜 읽씹하시죠?

**Comment by jk960903** [comment]
아 저거 한번 원인 봐보겠습니다 ~~
-----Original Message-----

**Comment by jk960903** [comment]
늦은 시간에 죄송합니다. 임시파일 삭제 완료했습니다.
-----Original Message-----

**Comment by jae637** [comment]
확인했습니다. 감사합니다.

**Comment by Hong-kee** [comment]
슬슬 프로젝트에 대한 아이디어와 정보수집을 해보는게 어떨까요? 간단하게 토이프로젝트로 시작해서 확장해보도록 합시다!

**Comment by jae637** [comment]
> 슬슬 프로젝트에 대한 아이디어와 정보수집을 해보는게 어떨까요? 간단하게 토이프로젝트로 시작해서 확장해보도록 합시다!

리포지토리 만들고 가볍게 계획서 짜고 실행해 보죠

해당 코멘트는 해당 이슈에 적합하지 않은것 같네요

**Comment by Hong-kee** [comment]
> > 슬슬 프로젝트에 대한 아이디어와 정보수집을 해보는게 어떨까요? 간단하게 토이프로젝트로 시작해서 확장해보도록 합시다!
> 
> 리포지토리 만들고 가볍게 계획서 짜고 실행해 보죠
> 
> 해당 코멘트는 해당 이슈에 적합하지 않은것 같네요

알겠습니다. 해당 리포지토리에서 언급하도록 하겠습니다.
